### ISSUE TITLE
TUI assumes black background

### ISSUE THREAD

**Issue by 0-wiz-0** [Etto48/HexPatch#108]
I've tried HexPatch 1.8.0 on an iTerm2 via ssh to a NetBSD server.
I prefer light mode (i.e. black text on white blackground).
When I start hexpatch and look at the help, I can read basically nothing.

It's fine to only prefer dark mode and default to it, but please make sure that the background really is black.

(It is possible that this works elsewhere and is only a problem because NetBSD because NetBSD has its own curses implementation, not ncurses; but most software works fine.)

(I found https://github.com/Etto48/HexPatch/blob/master/docs/SETTINGS.md in the meantime, but I think the default settings should be usable without configuration.)
<img width="2526" alt="Screenshot 2024-08-19 at 15 07 09" src="https://github.com/user-attachments/assets/646b048d-7f0e-4b10-94c2-37197eea5a97">

**Comment by 0-wiz-0** [comment]
Ok, same problem on macOS directly (in iTerm2), so NetBSD's not at fault :)
<img width="603" alt="Screenshot 2024-08-19 at 16 50 01" src="https://github.com/user-attachments/assets/858030d9-5603-45c7-b179-713ac9d82d79">

**Comment by 0323pin** [comment]
Packaged and merged into pkgsrc now, https://mail-index.netbsd.org/pkgsrc-changes/2024/08/20/msg305907.html

**Comment by Etto48** [comment]
Thank you @0-wiz-0 ! I would have never noticed, I will try to fix it asap. If you have already made a light theme, could you send it to me, it would save me some time.

**Comment by Etto48** [comment]
Thank you @0323pin ! (For what I understand the message is unrelated to this issue right?) Do you think it's appropriate to add the new installation method for NetBSD in the documentation?

**Comment by 0-wiz-0** [comment]
Thanks for looking at this, @Etto48 ! No, I haven't written a light theme yet.

**Comment by Etto48** [comment]
@0-wiz-0 no problem, I'm putting copilot at work, once I find a bit of time to test it I'll push a new release (if it works)

**Comment by 0323pin** [comment]
> Thank you @0323pin ! (For what I understand the message is unrelated to this issue right?) Do you think it's appropriate to add the new installation method for NetBSD in the documentation?

Yes, it's unrelated. It made sense to me, as I've packaged it and asked @0-wiz-0 to test the package before merging 😉

I can do a PR in the coming days to add installation notes.

**Comment by Etto48** [comment]
@0-wiz-0 unfortunately I'm not finding a functioning way to detect the background of the terminal, I think that the possible solution is one of:
- Changing the default theme to be visible both with black and white backgrounds (this might be challenging)
- Adding a setting to switch between dark and light theme
- Setting a black background with crossterm and handling everything as if it was black (it's not really a solution as it does not offer a white version + it's quite ugly with transparent backgrounds)
- Anything you suggest 😅

(I tried to use the crate termbg but it reports that my alacritty installation on windows (which I have set to have a white bg) as "Dark")

**Comment by Etto48** [comment]
So, I'm closing the issue with this merge because the light theme seems to be working, unfortunately on windows there is minimal support for automatic theme detection, I will wait a bit before making a new release to see if [dalance](https://github.com/dalance) can fix the library.
