### ISSUE TITLE
Cargo.lock is missing

### ISSUE THREAD

**Issue by orhun** [Etto48/HexPatch#111]
For binary projects `Cargo.lock` should be committed. See: <https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html>

It is also needed for the reproducibility of the distro packages.

**Comment by Etto48** [comment]
Will add asap, thank you!

**Comment by Etto48** [comment]
Woops, I've just seen your PR, I merged that, thank you again!
