### ISSUE TITLE
How to build on Windows?

### ISSUE THREAD

**Issue by teknalb** [Etto48/HexPatch#97]
**Describe what you would like to be improved or added**
I'd like some build instructions.

**If applicable describe why it needs to be improved**
Build Instructions unavailable.

This is the `cargo check` output.

```
cargo check
   Compiling keystone-engine v0.1.0
error: failed to run custom build command for `keystone-engine v0.1.0`

Caused by:
  process didn't exit successfully: `C:\Users\teknalb\HexPatch\target\debug\build\keystone-engine-1ee1c4dd1bee1105\build-script-build` (exit code: 101)
  --- stdout
  CMAKE_TOOLCHAIN_FILE_x86_64-pc-windows-msvc = None
  CMAKE_TOOLCHAIN_FILE_x86_64_pc_windows_msvc = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-pc-windows-msvc = None
  CMAKE_GENERATOR_x86_64_pc_windows_msvc = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-pc-windows-msvc = None
  CMAKE_PREFIX_PATH_x86_64_pc_windows_msvc = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_x86_64-pc-windows-msvc = None
  CMAKE_x86_64_pc_windows_msvc = None
  HOST_CMAKE = None
  CMAKE = None
  running: "cmake" "C:\\Users\\teknalb\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\keystone-engine-0.1.0\\keystone" "-G" "Visual Studio 17 2022" "-Thost=x64" "-Ax64" "-DCMAKE_INSTALL_LIBDIR=lib" "-DBUILD_LIBS_ONLY=1" "-DBUILD_SHARED_LIBS=OFF" "-DLLVM_TARGETS_TO_BUILD=all" "-DCMAKE_INSTALL_PREFIX=C:\\Users\\teknalb\\HexPatch\\target\\debug\\build\\keystone-engine-bf5bc90ccdcaefce\\out" "-DCMAKE_C_FLAGS= -nologo -MD -Brepro" "-DCMAKE_C_FLAGS_DEBUG= -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS= -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS_DEBUG= -nologo -MD -Brepro" "-DCMAKE_ASM_FLAGS= -nologo -MD -Brepro" "-DCMAKE_ASM_FLAGS_DEBUG= -nologo -MD -Brepro" "-DCMAKE_BUILD_TYPE=Debug"

  --- stderr
  CMake Error: Could not find CMAKE_ROOT !!!
  CMake has most likely not been installed correctly.
  Modules directory not found in

  CMake Error: Error executing cmake::LoadCache(). Aborting.

  thread 'main' panicked at C:\Users\teknalb\.cargo\registry\src\index.crates.io-6f17d22bba15001f\cmake-0.1.50\src\lib.rs:1098:5:

  command did not execute successfully, got: exit code: 1

  build script failed, must exit now
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I have both cmake and make installed and pointed to by `PATH` env var and I'd love to know how to correctly build on windows.

**Comment by Etto48** [comment]
I've never had this problem on my setup so I'll try to help based on what I found online:
- check if cmake is working correctly with `cmake --version`.
- check if the env variables `$CMAKE` or `$CMAKE_ROOT` are set, they should not be set unless if you have a custom path for the cmake binary, in that case `$CMAKE` should be set to the binary directory. For what I understand `$CMAKE_ROOT` is should not be set on Windows.
- double check the PATH just to be sure, make sure that the *binary* folder is on the PATH and not the parent directory. The default path should be `C:\Program Files\CMake\bin`
- try to set $CMAKE to the cmake binary path even if it's in the default location
- If nothing works try to uninstall and reinstall cmake, I tested the .msi available on [the official cmake download page](https://cmake.org/download/).

Let me know if you manage (and how) to solve this issue or what happens after the troubleshooting steps. I will edit the README to add the build requirements.

**Comment by Etto48** [comment]
@teknalb I will update the README accordingly. Unfortunately Capstone/Keystone are a pain to build and the rust bindings do not provide a clear list of dependencies. 

These libraries are needed in order to (dis)assemble executables and I could not find any substitute. 
Recently I was looking into [nyxstone](https://github.com/emproof-com/nyxstone) but it's build system requires even more uncommon dependencies (either LLVM or CMake + Ninja to build it). 

If you or anyone that reads this knows a valid alternative I'm happy to replace those two libs.
Thank you for the detailed comments and for trying HexPatch!

**Comment by Etto48** [comment]
Thank you @teknalb!

The first version of HexPatch actually used iced-x86 but I switched to Keystone to support more architectures, if they add more architectures I will probably swap back to iced.
